---
deployment:
  tasks:
    - export DEPLOYPATH=/home/reecemus/public_html/
    - /bin/cp -f index.html about.html artwork.html events.html recordings.html services.html contact.html favicon.png $DEPLOYPATH
    - /bin/cp -rf css js images $DEPLOYPATH

